// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHa73yh9YYuCULqxmxN5n196tTIIBQy4',
    appId: '1:499127086959:web:fd0ddbde42a55064a0029a',
    messagingSenderId: '499127086959',
    projectId: 'fir-2-b2e9d',
    authDomain: 'fir-2-b2e9d.firebaseapp.com',
    storageBucket: 'fir-2-b2e9d.appspot.com',
    measurementId: 'G-2JMJX8DYR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjqhq_NqmajbnCVQNUvwvZEteRU9Krta0',
    appId: '1:499127086959:android:5fdd96a8a09d147aa0029a',
    messagingSenderId: '499127086959',
    projectId: 'fir-2-b2e9d',
    storageBucket: 'fir-2-b2e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz945-PuZZOGqIewvrRyuzTC6u08GXrbc',
    appId: '1:499127086959:ios:6a65259fa44879bba0029a',
    messagingSenderId: '499127086959',
    projectId: 'fir-2-b2e9d',
    storageBucket: 'fir-2-b2e9d.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz945-PuZZOGqIewvrRyuzTC6u08GXrbc',
    appId: '1:499127086959:ios:6a65259fa44879bba0029a',
    messagingSenderId: '499127086959',
    projectId: 'fir-2-b2e9d',
    storageBucket: 'fir-2-b2e9d.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHa73yh9YYuCULqxmxN5n196tTIIBQy4',
    appId: '1:499127086959:web:6cbb62bb3e782638a0029a',
    messagingSenderId: '499127086959',
    projectId: 'fir-2-b2e9d',
    authDomain: 'fir-2-b2e9d.firebaseapp.com',
    storageBucket: 'fir-2-b2e9d.appspot.com',
    measurementId: 'G-6DK5LJ08TC',
  );
}
